### ISSUE TITLE
Icon set 

### ISSUE THREAD

**Issue by kepta** [sen-team8/da-dash#10]
Our application needs a library for icons.

This one looks promising to me.

http://dmfrancisco.github.io/react-icons/

@barkhabhojak have a look.

**Comment by barkhabhojak** [comment]
This is what I was looking at.

**Comment by kepta** [comment]
We will be using this library, can you include it to our codebase ?

**Comment by barkhabhojak** [comment]
A majority of the icons we'd need are there :) 
And yeah will do, still trying to figure out

**Comment by barkhabhojak** [comment]
@kepta I can't figure out how. I know the code is given and all but do you know of any tutorial?

**Comment by kepta** [comment]
tutorial for what?

**Comment by barkhabhojak** [comment]
Adding icons

**Comment by kepta** [comment]
umm, did you get the latest source code running on your laptop ?
I have added bootstrap in it

**Comment by barkhabhojak** [comment]
No, I'm still working on my own. I'll pull and integrate later

**Comment by kepta** [comment]
I would suggest first you get the code running, and then work on this issue

**Comment by barkhabhojak** [comment]
Unit testing first :P Integration later

**Comment by kepta** [comment]
@berzentine close this one, whenever you are done

**Comment by berzentine** [comment]
​Yes i ll​

Regards,
Nidhi Vyas

---

Junior undergraduate DA-IICT | Remote Research Intern CMU | _+91
8758-834909 | Google+ https://plus.google.com/+NidhiVyasberzentine/about_
