### ISSUE TITLE
Use of a router

### ISSUE THREAD

**Issue by kepta** [sen-team8/da-dash#11]
Our application would require routing logic.
I think [react-router](https://github.com/reactjs/react-router) be good for this task.

@nihitavr you views, and can you implement it ?

**Comment by nihitavr** [comment]
was doing that only!!!
that is y i was asking abt routing!!

**Comment by kepta** [comment]
https://css-tricks.com/learning-react-router/

**Comment by kepta** [comment]
and please update your branch, I have added some new stuff. 
don't forget to do `npm install`

**Comment by nihitavr** [comment]
i know how it works

**Comment by kepta** [comment]
Was successfully implemented.
