### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by Deergh** [sen-team8/da-dash#19]

**Comment by kepta** [comment]
https://github.com/openstreetmap/iD/commit/eebdad79ed9dd082de7068adbefde9a1d266f8fd

**Comment by Deergh** [comment]
@kepta kushan i made it in different way..

**Comment by kepta** [comment]
and?

**Comment by Deergh** [comment]
@kepta i ll show you in meeting i made it like in this format
http://www.sqa.org.uk/e-learning/ProfIssues03CD/page_04.htm
